name: cps330
channels:
  - defaults
dependencies:
  - python
  - ipykernel # Better REPL
  - pip # packages not in environment
  - numpy # math
  - graphviz # graph visualization
  - matplotlib # plotting
  - pandas # data manipulation
  - tensorflow # neural networks
  - scikit-learn # machine learning
  - keras # ANN framework
  - pip:
      - PyX # PDF utility
      - scapy # packet manipulation
